POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "batman"
}


### username too short
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "Luke"
}


### Testing rabbitmq publishing
POST http://localhost:8080/rabbit
Content-Type: application/json

{
  "text": "Hello, RabbitMQ!"
}